# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: problemdef.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='problemdef.proto',
  package='',
  serialized_pb=_b('\n\x10problemdef.proto\"-\n\x11PlanProblemVarVal\x12\x0b\n\x03var\x18\x01 \x02(\x05\x12\x0b\n\x03val\x18\x02 \x02(\x05\"\x1f\n\x10PlanProblemState\x12\x0b\n\x03val\x18\x01 \x03(\x05\"7\n\x14PlanProblemPartState\x12\x1f\n\x03val\x18\x01 \x03(\x0b\x32\x12.PlanProblemVarVal\"T\n\x0ePlanProblemVar\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05range\x18\x02 \x02(\x05\x12\x11\n\tfact_name\x18\x03 \x03(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\"4\n\x10PlanProblemMutex\x12 \n\x04\x66\x61\x63t\x18\x01 \x03(\x0b\x32\x12.PlanProblemVarVal\"\\\n\x12PlanProblemCondEff\x12\"\n\x03pre\x18\x01 \x02(\x0b\x32\x15.PlanProblemPartState\x12\"\n\x03\x65\x66\x66\x18\x02 \x02(\x0b\x32\x15.PlanProblemPartState\"\xd6\x01\n\x13PlanProblemOperator\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0c\n\x04\x63ost\x18\x02 \x02(\x05\x12\"\n\x03pre\x18\x03 \x02(\x0b\x32\x15.PlanProblemPartState\x12\"\n\x03\x65\x66\x66\x18\x04 \x02(\x0b\x32\x15.PlanProblemPartState\x12%\n\x08\x63ond_eff\x18\x05 \x03(\x0b\x32\x13.PlanProblemCondEff\x12\r\n\x05owner\x18\x06 \x01(\x05\x12\x11\n\tglobal_id\x18\x07 \x01(\x05\x12\x12\n\nis_private\x18\x08 \x01(\x08\"\xaa\x02\n\x0bPlanProblem\x12\x0f\n\x07version\x18\x01 \x02(\x05\x12\x1c\n\x03var\x18\x02 \x03(\x0b\x32\x0f.PlanProblemVar\x12 \n\x05mutex\x18\x03 \x03(\x0b\x32\x11.PlanProblemMutex\x12%\n\ninit_state\x18\x04 \x02(\x0b\x32\x11.PlanProblemState\x12#\n\x04goal\x18\x05 \x02(\x0b\x32\x15.PlanProblemPartState\x12&\n\x08operator\x18\x06 \x03(\x0b\x32\x14.PlanProblemOperator\x12\x12\n\nagent_name\x18\x07 \x03(\t\x12\x30\n\x12projected_operator\x18\x08 \x03(\x0b\x32\x14.PlanProblemOperator\x12\x10\n\x08\x61gent_id\x18\t \x01(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PLANPROBLEMVARVAL = _descriptor.Descriptor(
  name='PlanProblemVarVal',
  full_name='PlanProblemVarVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='var', full_name='PlanProblemVarVal.var', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='val', full_name='PlanProblemVarVal.val', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=65,
)


_PLANPROBLEMSTATE = _descriptor.Descriptor(
  name='PlanProblemState',
  full_name='PlanProblemState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='PlanProblemState.val', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=98,
)


_PLANPROBLEMPARTSTATE = _descriptor.Descriptor(
  name='PlanProblemPartState',
  full_name='PlanProblemPartState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='PlanProblemPartState.val', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=155,
)


_PLANPROBLEMVAR = _descriptor.Descriptor(
  name='PlanProblemVar',
  full_name='PlanProblemVar',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PlanProblemVar.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='range', full_name='PlanProblemVar.range', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='fact_name', full_name='PlanProblemVar.fact_name', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_private', full_name='PlanProblemVar.is_private', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=241,
)


_PLANPROBLEMMUTEX = _descriptor.Descriptor(
  name='PlanProblemMutex',
  full_name='PlanProblemMutex',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='fact', full_name='PlanProblemMutex.fact', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=295,
)


_PLANPROBLEMCONDEFF = _descriptor.Descriptor(
  name='PlanProblemCondEff',
  full_name='PlanProblemCondEff',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pre', full_name='PlanProblemCondEff.pre', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eff', full_name='PlanProblemCondEff.eff', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=389,
)


_PLANPROBLEMOPERATOR = _descriptor.Descriptor(
  name='PlanProblemOperator',
  full_name='PlanProblemOperator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PlanProblemOperator.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cost', full_name='PlanProblemOperator.cost', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pre', full_name='PlanProblemOperator.pre', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='eff', full_name='PlanProblemOperator.eff', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cond_eff', full_name='PlanProblemOperator.cond_eff', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='owner', full_name='PlanProblemOperator.owner', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='global_id', full_name='PlanProblemOperator.global_id', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_private', full_name='PlanProblemOperator.is_private', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=606,
)


_PLANPROBLEM = _descriptor.Descriptor(
  name='PlanProblem',
  full_name='PlanProblem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='PlanProblem.version', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='var', full_name='PlanProblem.var', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mutex', full_name='PlanProblem.mutex', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='init_state', full_name='PlanProblem.init_state', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='goal', full_name='PlanProblem.goal', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='operator', full_name='PlanProblem.operator', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agent_name', full_name='PlanProblem.agent_name', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='projected_operator', full_name='PlanProblem.projected_operator', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='PlanProblem.agent_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=907,
)

_PLANPROBLEMPARTSTATE.fields_by_name['val'].message_type = _PLANPROBLEMVARVAL
_PLANPROBLEMMUTEX.fields_by_name['fact'].message_type = _PLANPROBLEMVARVAL
_PLANPROBLEMCONDEFF.fields_by_name['pre'].message_type = _PLANPROBLEMPARTSTATE
_PLANPROBLEMCONDEFF.fields_by_name['eff'].message_type = _PLANPROBLEMPARTSTATE
_PLANPROBLEMOPERATOR.fields_by_name['pre'].message_type = _PLANPROBLEMPARTSTATE
_PLANPROBLEMOPERATOR.fields_by_name['eff'].message_type = _PLANPROBLEMPARTSTATE
_PLANPROBLEMOPERATOR.fields_by_name['cond_eff'].message_type = _PLANPROBLEMCONDEFF
_PLANPROBLEM.fields_by_name['var'].message_type = _PLANPROBLEMVAR
_PLANPROBLEM.fields_by_name['mutex'].message_type = _PLANPROBLEMMUTEX
_PLANPROBLEM.fields_by_name['init_state'].message_type = _PLANPROBLEMSTATE
_PLANPROBLEM.fields_by_name['goal'].message_type = _PLANPROBLEMPARTSTATE
_PLANPROBLEM.fields_by_name['operator'].message_type = _PLANPROBLEMOPERATOR
_PLANPROBLEM.fields_by_name['projected_operator'].message_type = _PLANPROBLEMOPERATOR
DESCRIPTOR.message_types_by_name['PlanProblemVarVal'] = _PLANPROBLEMVARVAL
DESCRIPTOR.message_types_by_name['PlanProblemState'] = _PLANPROBLEMSTATE
DESCRIPTOR.message_types_by_name['PlanProblemPartState'] = _PLANPROBLEMPARTSTATE
DESCRIPTOR.message_types_by_name['PlanProblemVar'] = _PLANPROBLEMVAR
DESCRIPTOR.message_types_by_name['PlanProblemMutex'] = _PLANPROBLEMMUTEX
DESCRIPTOR.message_types_by_name['PlanProblemCondEff'] = _PLANPROBLEMCONDEFF
DESCRIPTOR.message_types_by_name['PlanProblemOperator'] = _PLANPROBLEMOPERATOR
DESCRIPTOR.message_types_by_name['PlanProblem'] = _PLANPROBLEM

PlanProblemVarVal = _reflection.GeneratedProtocolMessageType('PlanProblemVarVal', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMVARVAL,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemVarVal)
  ))
_sym_db.RegisterMessage(PlanProblemVarVal)

PlanProblemState = _reflection.GeneratedProtocolMessageType('PlanProblemState', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMSTATE,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemState)
  ))
_sym_db.RegisterMessage(PlanProblemState)

PlanProblemPartState = _reflection.GeneratedProtocolMessageType('PlanProblemPartState', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMPARTSTATE,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemPartState)
  ))
_sym_db.RegisterMessage(PlanProblemPartState)

PlanProblemVar = _reflection.GeneratedProtocolMessageType('PlanProblemVar', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMVAR,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemVar)
  ))
_sym_db.RegisterMessage(PlanProblemVar)

PlanProblemMutex = _reflection.GeneratedProtocolMessageType('PlanProblemMutex', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMMUTEX,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemMutex)
  ))
_sym_db.RegisterMessage(PlanProblemMutex)

PlanProblemCondEff = _reflection.GeneratedProtocolMessageType('PlanProblemCondEff', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMCONDEFF,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemCondEff)
  ))
_sym_db.RegisterMessage(PlanProblemCondEff)

PlanProblemOperator = _reflection.GeneratedProtocolMessageType('PlanProblemOperator', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEMOPERATOR,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblemOperator)
  ))
_sym_db.RegisterMessage(PlanProblemOperator)

PlanProblem = _reflection.GeneratedProtocolMessageType('PlanProblem', (_message.Message,), dict(
  DESCRIPTOR = _PLANPROBLEM,
  __module__ = 'problemdef_pb2'
  # @@protoc_insertion_point(class_scope:PlanProblem)
  ))
_sym_db.RegisterMessage(PlanProblem)


# @@protoc_insertion_point(module_scope)
