#!/usr/bin/env python3
# -*- coding: utf-8 -*-

configs = dict()

# DEFAULT
configs.update({
    "mafs":   ["-s", "-s mafs-g  -h ff -l 1", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg":   ["-s", "-s dmt-bfs -h ff -l 1", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb":   ["-s", "-s dmt-gus -h ff -l 1", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-tcp":   ["-s", "-s mafs-g  -h ff -l 1", "--heuristic", "ff", "--planlimit", "1"],
    "mafs-tcp+":   ["-s", "-s mafs-g  -h ff -l 1", "--heuristic", "ff", "--planlimit", "100"],
    "dmtg-tcp":   ["-s", "-s dmt-bfs -h ff -l 1", "--heuristic", "ff", "--planlimit", "1"],
    "dmtb-tcp":   ["-s", "-s dmt-gus -h ff -l 1", "--heuristic", "ff", "--planlimit", "1"],
    "dmtg-unit": ["-s", "-s dmt-bfs -h ff -l 1 --costtype 1", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-gc": ["-s", "-s dmt-bfs -h gc -l 1 --costtype 1", "--heuristic", "gc", "--threaded", "--planlimit", "1"],
})

configs.update({
    # costtype: normal min one (2)
    "mafs-ff-lazy-r-t100": ["-s", "-s mafs-g -h ff -l 100 -z -r",  "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-t100":   ["-s", "-s mafs-g -h ff -l 100 -z",     "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-r":      ["-s", "-s mafs-g -h ff -z -r",         "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy":        ["-s", "-s mafs-g -h ff -z",            "--heuristic", "ff", "--threaded"],
    "mafs-ff-r-t100":      ["-s", "-s mafs-g -h ff -l 100 -r",     "--heuristic", "ff", "--threaded"],
    "mafs-ff-t100":        ["-s", "-s mafs-g -h ff -l 100",        "--heuristic", "ff", "--threaded"],
    "mafs-ff":             ["-s", "-s mafs-g -h ff",               "--heuristic", "ff", "--threaded"],
    "mafs-ff-r":           ["-s", "-s mafs-g -h ff -r",            "--heuristic", "ff", "--threaded"],
    "dmtg-ff-lazy-t100":   ["-s", "-s dmt-bfs -h ff -l 100 -z",    "--heuristic", "ff", "--threaded"],
    "dmtg-ff-lazy":        ["-s", "-s dmt-bfs -h ff -z",           "--heuristic", "ff", "--threaded"],
    "dmtg-ff-t100":        ["-s", "-s dmt-bfs -h ff -l 100",       "--heuristic", "ff", "--threaded"],
    "dmtg-ff":             ["-s", "-s dmt-bfs -h ff",              "--heuristic", "ff", "--threaded"],
    # costtype: (n)ormal (0)
    "mafs-ff-lazy-r-t100-n": ["-s", "-s mafs-g -h ff -l 100 -z -r --costtype 0",  "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-t100-n":   ["-s", "-s mafs-g -h ff -l 100 -z --costtype 0",     "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-r-n":      ["-s", "-s mafs-g -h ff -z -r --costtype 0",         "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-n":        ["-s", "-s mafs-g -h ff -z --costtype 0",            "--heuristic", "ff", "--threaded"],
    "mafs-ff-r-t100-n":      ["-s", "-s mafs-g -h ff -l 100 -r --costtype 0",     "--heuristic", "ff", "--threaded"],
    "mafs-ff-t100-n":        ["-s", "-s mafs-g -h ff -l 100 --costtype 0",        "--heuristic", "ff", "--threaded"],
    "mafs-ff-n":             ["-s", "-s mafs-g -h ff --costtype 0",               "--heuristic", "ff", "--threaded"],
    "mafs-ff-r-n":           ["-s", "-s mafs-g -h ff -r --costtype 0",            "--heuristic", "ff", "--threaded"],
    "dmtg-ff-lazy-t100-n":   ["-s", "-s dmt-bfs -h ff -l 100 -z --costtype 0",    "--heuristic", "ff", "--threaded"],
    "dmtg-ff-lazy-n":        ["-s", "-s dmt-bfs -h ff -z --costtype 0",           "--heuristic", "ff", "--threaded"],
    "dmtg-ff-t100-n":        ["-s", "-s dmt-bfs -h ff -l 100 --costtype 0",       "--heuristic", "ff", "--threaded"],
    "dmtg-ff-n":             ["-s", "-s dmt-bfs -h ff --costtype 0",              "--heuristic", "ff", "--threaded"],
    # costtype: (u)nit (1)
    "mafs-ff-lazy-r-t100-u": ["-s", "-s mafs-g -h ff -l 100 -z -r --costtype 1",  "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-t100-u":   ["-s", "-s mafs-g -h ff -l 100 -z --costtype 1",     "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-r-u":      ["-s", "-s mafs-g -h ff -z -r --costtype 1",         "--heuristic", "ff", "--threaded"],
    "mafs-ff-lazy-u":        ["-s", "-s mafs-g -h ff -z --costtype 1",            "--heuristic", "ff", "--threaded"],
    "mafs-ff-r-t100-u":      ["-s", "-s mafs-g -h ff -l 100 -r --costtype 1",     "--heuristic", "ff", "--threaded"],
    "mafs-ff-t100-u":        ["-s", "-s mafs-g -h ff -l 100 --costtype 1",        "--heuristic", "ff", "--threaded"],
    "mafs-ff-u":             ["-s", "-s mafs-g -h ff --costtype 1",               "--heuristic", "ff", "--threaded"],
    "mafs-ff-r-u":           ["-s", "-s mafs-g -h ff -r --costtype 1",            "--heuristic", "ff", "--threaded"],
    "dmtg-ff-lazy-t100-u":   ["-s", "-s dmt-bfs -h ff -l 100 -z --costtype 1",    "--heuristic", "ff", "--threaded"],
    "dmtg-ff-lazy-u":        ["-s", "-s dmt-bfs -h ff -z --costtype 1",           "--heuristic", "ff", "--threaded"],
    "dmtg-ff-t100-u":        ["-s", "-s dmt-bfs -h ff -l 100 --costtype 1",       "--heuristic", "ff", "--threaded"],
    "dmtg-ff-u":             ["-s", "-s dmt-bfs -h ff --costtype 1",              "--heuristic", "ff", "--threaded"],

    # DMT disregard
    "dmtg-ff-d100":      ["-s", "-s dmt-bfs -h ff --costtype 0 -d 100",        "--heuristic", "ff", "--threaded"],
    "dmtg-ff-t100-d100": ["-s", "-s dmt-bfs -h ff --costtype 0 -d 100 -l 100", "--heuristic", "ff", "--threaded"],
    "dmtb-ff-d100":      ["-s", "-s dmt-gus -h ff --costtype 0 -d 100",        "--heuristic", "ff", "--threaded"],
    "dmtb-ff-t100-d100": ["-s", "-s dmt-gus -h ff --costtype 0 -d 100 -l 100", "--heuristic", "ff", "--threaded"],
    "dmtb-ff":           ["-s", "-s dmt-gus -h ff --costtype 0",               "--heuristic", "ff", "--threaded"],
    "dmtb-ff-100":       ["-s", "-s dmt-gus -h ff --costtype 0 -l 100",        "--heuristic", "ff", "--threaded"],

    # BLIND
    "mafs-blind": ["-s", "-s mafs-g -h blind", "--heuristic", "blind", "--threaded"],
    "mafs-gc": ["-s", "-s mafs-g -h gc", "--heuristic", "gc", "--threaded"],
})

# MAKESPAN configs
configs.update({
    "dmtmakespan-baseline": ["--search", "-s dmtg -h ff", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-greedy": ["--search", "-s dmtmakespan-weighted -h ff -w 0", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-optimal": ["--search", "-s dmtmakespan-weighted -h ff -W 0", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-low": ["--search", "-s dmtmakespan-weighted -h ff -W 0.1", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-balanced": ["--search", "-s dmtmakespan-weighted -h ff -w 1 -W 1", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-high": ["--search", "-s dmtmakespan-weighted -h ff -W 10", "--heuristic", "ff", "--threaded"],

    "dmtmakespan-greedy-n":     ["--search", "-s dmtmakespan-weighted -h ff -w 0      -n", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-optimal-n":    ["--search", "-s dmtmakespan-weighted -h ff -W 0      -n", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-low-n":        ["--search", "-s dmtmakespan-weighted -h ff -W 0.1    -n", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-balanced-n":   ["--search", "-s dmtmakespan-weighted -h ff -w 1 -W 1 -n", "--heuristic", "ff", "--threaded"],
    "dmtmakespan-high-n":       ["--search", "-s dmtmakespan-weighted -h ff -W 10     -n", "--heuristic", "ff", "--threaded"],
})

# CONFIGS FOR SOCS19 PAPER
configs.update({
    # DMTB
    "dmtb-ff1-t1":      ["-s", "-s dmt-gus -h ff -l 1",        "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t1-d100": ["-s", "-s dmt-gus -h ff -l 1 -d 100", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t10":  ["-s", "-s dmt-gus -h ff -l 10",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t20":  ["-s", "-s dmt-gus -h ff -l 20",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t30":  ["-s", "-s dmt-gus -h ff -l 30",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t40":  ["-s", "-s dmt-gus -h ff -l 40",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t50":  ["-s", "-s dmt-gus -h ff -l 50",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t60":  ["-s", "-s dmt-gus -h ff -l 60",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t70":  ["-s", "-s dmt-gus -h ff -l 70",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t80":  ["-s", "-s dmt-gus -h ff -l 80",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t90":  ["-s", "-s dmt-gus -h ff -l 90",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t100": ["-s", "-s dmt-gus -h ff -l 100", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t110": ["-s", "-s dmt-gus -h ff -l 110", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t120": ["-s", "-s dmt-gus -h ff -l 120", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t130": ["-s", "-s dmt-gus -h ff -l 130", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t140": ["-s", "-s dmt-gus -h ff -l 140", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t150": ["-s", "-s dmt-gus -h ff -l 150", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t160": ["-s", "-s dmt-gus -h ff -l 160", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t170": ["-s", "-s dmt-gus -h ff -l 170", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t180": ["-s", "-s dmt-gus -h ff -l 180", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t190": ["-s", "-s dmt-gus -h ff -l 190", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t200": ["-s", "-s dmt-gus -h ff -l 200", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t210": ["-s", "-s dmt-gus -h ff -l 210", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t220": ["-s", "-s dmt-gus -h ff -l 220", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t230": ["-s", "-s dmt-gus -h ff -l 230", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t240": ["-s", "-s dmt-gus -h ff -l 240", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t250": ["-s", "-s dmt-gus -h ff -l 250", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t260": ["-s", "-s dmt-gus -h ff -l 260", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t270": ["-s", "-s dmt-gus -h ff -l 270", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t280": ["-s", "-s dmt-gus -h ff -l 280", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t290": ["-s", "-s dmt-gus -h ff -l 290", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t300": ["-s", "-s dmt-gus -h ff -l 300", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t310": ["-s", "-s dmt-gus -h ff -l 310", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t320": ["-s", "-s dmt-gus -h ff -l 320", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t330": ["-s", "-s dmt-gus -h ff -l 330", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t340": ["-s", "-s dmt-gus -h ff -l 340", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t350": ["-s", "-s dmt-gus -h ff -l 350", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t360": ["-s", "-s dmt-gus -h ff -l 360", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t370": ["-s", "-s dmt-gus -h ff -l 370", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t380": ["-s", "-s dmt-gus -h ff -l 380", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t390": ["-s", "-s dmt-gus -h ff -l 390", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtb-ff1-t400": ["-s", "-s dmt-gus -h ff -l 400", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    # DMTG
    "dmtg-ff1-t1-d100": ["-s", "-s dmt-bfs -h ff -l 1 -d 100", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t1":   ["-s", "-s dmt-bfs -h ff -l 1",   "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t10":  ["-s", "-s dmt-bfs -h ff -l 10",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t20":  ["-s", "-s dmt-bfs -h ff -l 20",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t30":  ["-s", "-s dmt-bfs -h ff -l 30",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t40":  ["-s", "-s dmt-bfs -h ff -l 40",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t50":  ["-s", "-s dmt-bfs -h ff -l 50",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t60":  ["-s", "-s dmt-bfs -h ff -l 60",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t70":  ["-s", "-s dmt-bfs -h ff -l 70",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t80":  ["-s", "-s dmt-bfs -h ff -l 80",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t90":  ["-s", "-s dmt-bfs -h ff -l 90",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t100": ["-s", "-s dmt-bfs -h ff -l 100", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t110": ["-s", "-s dmt-bfs -h ff -l 110", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t120": ["-s", "-s dmt-bfs -h ff -l 120", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t130": ["-s", "-s dmt-bfs -h ff -l 130", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t140": ["-s", "-s dmt-bfs -h ff -l 140", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t150": ["-s", "-s dmt-bfs -h ff -l 150", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t160": ["-s", "-s dmt-bfs -h ff -l 160", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t170": ["-s", "-s dmt-bfs -h ff -l 170", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t180": ["-s", "-s dmt-bfs -h ff -l 180", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t190": ["-s", "-s dmt-bfs -h ff -l 190", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t200": ["-s", "-s dmt-bfs -h ff -l 200", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t210": ["-s", "-s dmt-bfs -h ff -l 210", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t220": ["-s", "-s dmt-bfs -h ff -l 220", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t230": ["-s", "-s dmt-bfs -h ff -l 230", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t240": ["-s", "-s dmt-bfs -h ff -l 240", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t250": ["-s", "-s dmt-bfs -h ff -l 250", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t260": ["-s", "-s dmt-bfs -h ff -l 260", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t270": ["-s", "-s dmt-bfs -h ff -l 270", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t280": ["-s", "-s dmt-bfs -h ff -l 280", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t290": ["-s", "-s dmt-bfs -h ff -l 290", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t300": ["-s", "-s dmt-bfs -h ff -l 300", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t310": ["-s", "-s dmt-bfs -h ff -l 310", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t320": ["-s", "-s dmt-bfs -h ff -l 320", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t330": ["-s", "-s dmt-bfs -h ff -l 330", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t340": ["-s", "-s dmt-bfs -h ff -l 340", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t350": ["-s", "-s dmt-bfs -h ff -l 350", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t360": ["-s", "-s dmt-bfs -h ff -l 360", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t370": ["-s", "-s dmt-bfs -h ff -l 370", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t380": ["-s", "-s dmt-bfs -h ff -l 380", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t390": ["-s", "-s dmt-bfs -h ff -l 390", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "dmtg-ff1-t400": ["-s", "-s dmt-bfs -h ff -l 400", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    # MAFS
    "mafs-ff1-t1":   ["-s", "-s mafs-g -h ff -l 1",   "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t10":  ["-s", "-s mafs-g -h ff -l 10",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t20":  ["-s", "-s mafs-g -h ff -l 20",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t30":  ["-s", "-s mafs-g -h ff -l 30",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t40":  ["-s", "-s mafs-g -h ff -l 40",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t50":  ["-s", "-s mafs-g -h ff -l 50",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t60":  ["-s", "-s mafs-g -h ff -l 60",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t70":  ["-s", "-s mafs-g -h ff -l 70",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t80":  ["-s", "-s mafs-g -h ff -l 80",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t90":  ["-s", "-s mafs-g -h ff -l 90",  "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t100": ["-s", "-s mafs-g -h ff -l 100", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t110": ["-s", "-s mafs-g -h ff -l 110", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t120": ["-s", "-s mafs-g -h ff -l 120", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t130": ["-s", "-s mafs-g -h ff -l 130", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t140": ["-s", "-s mafs-g -h ff -l 140", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t150": ["-s", "-s mafs-g -h ff -l 150", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t160": ["-s", "-s mafs-g -h ff -l 160", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t170": ["-s", "-s mafs-g -h ff -l 170", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t180": ["-s", "-s mafs-g -h ff -l 180", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t190": ["-s", "-s mafs-g -h ff -l 190", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t200": ["-s", "-s mafs-g -h ff -l 200", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t210": ["-s", "-s mafs-g -h ff -l 210", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t220": ["-s", "-s mafs-g -h ff -l 220", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t230": ["-s", "-s mafs-g -h ff -l 230", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t240": ["-s", "-s mafs-g -h ff -l 240", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t250": ["-s", "-s mafs-g -h ff -l 250", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t260": ["-s", "-s mafs-g -h ff -l 260", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t270": ["-s", "-s mafs-g -h ff -l 270", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t280": ["-s", "-s mafs-g -h ff -l 280", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t290": ["-s", "-s mafs-g -h ff -l 290", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t300": ["-s", "-s mafs-g -h ff -l 300", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t310": ["-s", "-s mafs-g -h ff -l 310", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t320": ["-s", "-s mafs-g -h ff -l 320", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t330": ["-s", "-s mafs-g -h ff -l 330", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t340": ["-s", "-s mafs-g -h ff -l 340", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t350": ["-s", "-s mafs-g -h ff -l 350", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t360": ["-s", "-s mafs-g -h ff -l 360", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t370": ["-s", "-s mafs-g -h ff -l 370", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t380": ["-s", "-s mafs-g -h ff -l 380", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t390": ["-s", "-s mafs-g -h ff -l 390", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
    "mafs-ff1-t400": ["-s", "-s mafs-g -h ff -l 400", "--heuristic", "ff", "--threaded", "--planlimit", "1"],
})

# STUBBORN SETS configs
configs.update({
    "mafs-ff-sss":      ["-s", "-s mafs-g  -h ff",          "--pruning", "sss", "--heuristic", "ff", "--threaded"],
    "dmtg-ff-sss":      ["-s", "-s dmt-bfs -h ff",          "--pruning", "sss", "--heuristic", "ff", "--threaded"],
    "dmtg-ff-t100-sss": ["-s", "-s dmt-bfs -h ff -l 100",   "--pruning", "sss", "--heuristic", "ff", "--threaded"],
})

# YOUR CONFIGS
configs.update({
})
# ALARM: don't forget adding COMAS at the end of each dict entry
