python3 driver/createjobs.py -t \
    benchmarks/compiled/blocksworld/probBLOCKS-{9..11}-{0..2}/ \
    benchmarks/compiled/blocksworld/probBLOCKS-{12..16}-{0..1}/ \
    benchmarks/compiled/blocksworld/probBLOCKS-17-0/ \
    benchmarks/compiled/depot/pfile{1..20}/ \
    benchmarks/compiled/driverlog/pfile{1..20}/ \
    benchmarks/compiled/elevators08/p0{1..9}/ \
    benchmarks/compiled/elevators08/p{10..20}/ \
    benchmarks/compiled/logistics00/probLOGISTICS-{8..15}-{0,1}/ \
    benchmarks/compiled/logistics00/probLOGISTICS-{4..7}-0/ \
    benchmarks/compiled/productionsite/4-10-1-1/ \
    benchmarks/compiled/productionsite/4-10-2-2/ \
    benchmarks/compiled/productionsite/4-10-3-3/ \
    benchmarks/compiled/productionsite/4-10-4-4/ \
    benchmarks/compiled/productionsite/4-4-1-1/ \
    benchmarks/compiled/productionsite/4-4-2-2/ \
    benchmarks/compiled/productionsite/4-4-3-3/ \
    benchmarks/compiled/productionsite/4-4-4-4/ \
    benchmarks/compiled/productionsite/4-4-5-5/ \
    benchmarks/compiled/productionsite/4-4-6-6/ \
    benchmarks/compiled/productionsite/4-5-1-1/ \
    benchmarks/compiled/productionsite/4-5-2-2/ \
    benchmarks/compiled/productionsite/4-5-3-3/ \
    benchmarks/compiled/productionsite/4-5-4-4/ \
    benchmarks/compiled/productionsite/4-5-5-5/ \
    benchmarks/compiled/productionsite/4-5-6-6/ \
    benchmarks/compiled/productionsite/4-6-1-1/ \
    benchmarks/compiled/productionsite/4-6-2-2/ \
    benchmarks/compiled/productionsite/4-6-3-3/ \
    benchmarks/compiled/productionsite/4-6-4-4/ \
    benchmarks/compiled/productionsite/4-6-5-5/ \
    benchmarks/compiled/productionsite/4-6-6-6/ \
    benchmarks/compiled/productionsite/4-7-1-1/ \
    benchmarks/compiled/productionsite/4-7-2-2/ \
    benchmarks/compiled/productionsite/4-7-3-3/ \
    benchmarks/compiled/productionsite/4-7-4-4/ \
    benchmarks/compiled/productionsite/4-7-5-5/ \
    benchmarks/compiled/productionsite/4-7-6-6/ \
    benchmarks/compiled/productionsite/4-8-1-1/ \
    benchmarks/compiled/productionsite/4-8-2-2/ \
    benchmarks/compiled/productionsite/4-8-3-3/ \
    benchmarks/compiled/productionsite/4-8-4-4/ \
    benchmarks/compiled/productionsite/4-8-5-5/ \
    benchmarks/compiled/productionsite/4-8-6-6/ \
    benchmarks/compiled/productionsite/4-9-1-1/ \
    benchmarks/compiled/productionsite/4-9-2-2/ \
    benchmarks/compiled/productionsite/4-9-3-3/ \
    benchmarks/compiled/productionsite/4-9-4-4/ \
    benchmarks/compiled/productionsite/4-9-5-5/ \
    benchmarks/compiled/productionsite/4-9-6-6/ \
    benchmarks/compiled/rovers/p{10..29}/ \
    benchmarks/compiled/satellites/p05-pfile5/ \
    benchmarks/compiled/satellites/p08-pfile8/ \
    benchmarks/compiled/satellites/p11-pfile11/ \
    benchmarks/compiled/satellites/p14-pfile14/ \
    benchmarks/compiled/satellites/p18-pfile18/ \
    benchmarks/compiled/satellites/p21-HC-pfile1/ \
    benchmarks/compiled/satellites/p24-HC-pfile4/ \
    benchmarks/compiled/satellites/p06-pfile6/ \
    benchmarks/compiled/satellites/p09-pfile9/ \
    benchmarks/compiled/satellites/p12-pfile12/ \
    benchmarks/compiled/satellites/p15-pfile15/ \
    benchmarks/compiled/satellites/p19-pfile19/ \
    benchmarks/compiled/satellites/p22-HC-pfile2/ \
    benchmarks/compiled/satellites/p25-HC-pfile5/ \
    benchmarks/compiled/satellites/p07-pfile7/ \
    benchmarks/compiled/satellites/p10-pfile10/ \
    benchmarks/compiled/satellites/p13-pfile13/ \
    benchmarks/compiled/satellites/p16-pfile16/ \
    benchmarks/compiled/satellites/p20-pfile20/ \
    benchmarks/compiled/satellites/p23-HC-pfile3/ \
    benchmarks/compiled/sokoban/p0{1..9}{"",-1}/ \
    benchmarks/compiled/sokoban/p10{"",-1}/ \
    benchmarks/compiled/taxi/p0{1..9}/ \
    benchmarks/compiled/taxi/p{10..20}/ \
    benchmarks/compiled/wireless/p0{1..9}/ \
    benchmarks/compiled/wireless/p{10..20}/ \
    benchmarks/compiled/woodworking08/p0{1..9}/ \
    benchmarks/compiled/woodworking08/p{10..20}/ \
    benchmarks/compiled/zenotravel/pfile{3..10}/ \
    benchmarks/compiled/zenotravel/pfile{12..23}/ \
    "${@:1}"
